[project]
name = "paragraph-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aleksandr Basov", email = "sasha4ka99991@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "maxapi>=1.2.2",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
]

[project.scripts]
paragraph-ai = "paragraph_ai:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
