name: 'Build and push a container to GHCR'

permissions:
  contents: read
  packages: write

on:
    push:
      branches: ["master", "test"]
    

env:
    CONTAINER_NAME: 'sasha4ka/paragraph-ai'

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        
        steps:
            - name: setup checkout
              uses: actions/checkout@v4
            
            - name: GitHub (GHCR) login
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN}}
            
            - name: Docker build and push
              run: |
                if [ "$GITHUB_REF_NAME" = "master" ]; then
                  BRANCH_TAG=release
                else
                  BRANCH_TAG=test
                fi

                IMAGE="ghcr.io/${{ env.CONTAINER_NAME }}"
                docker build -t "$IMAGE:latest" -t "$IMAGE:$BRANCH_TAG" .
                docker push "$IMAGE:latest"
                docker push "$IMAGE:$BRANCH_TAG"

